stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/diabetes_binary.csv
      - src/preprocessing.py
    outs:
      - data/diabetes_preprocessing_pipeline.pkl
      - data/diabetes_train.csv
      - data/diabetes_val.csv
      - data/diabetes_test.csv
